### ISSUE TITLE
Cannot determine license

### ISSUE THREAD

**Issue by YoanaIvanova** [gregra81/jqzoom#1]
Hi, I see this repository hasn't been updated since 2014, but nevertheless...

I'm trying to add jqzoom 2.3.0 as a [bower webjar](http://www.webjars.org/bower) and I get the following error:

> Deploy Log
> 
> Failed! All attempts to determine a license have been exhausted. The bower.json did not contain a spec-compliant license definition and the license could not be determined by trolling through the GitHub repo. This problem will likely need to be resolved by working with the library maintainers directly. If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues  
> Determined Artifact Name: jqzoom
> Starting Deploy

Any chance you could update the bower.json file with a spec-compliant license definition? Thanks in advance!

**Comment by gregra81** [comment]
@YoanaIvanova - Updated with the `BSD-3-Clause` license

**Comment by YoanaIvanova** [comment]
@gregra81 Thanks for the update. There's still a problem, though. In http://www.webjars.org/bower , I click on "Add New Bower WebJar" and input the link to your GitHub repo. It doesn't find any versions:

![jqzoom webjar](https://cloud.githubusercontent.com/assets/15999515/18125410/d0cd04d2-6f7e-11e6-895b-ec11059cb2b5.png)

When I click on "Deploy", the process hangs at the first step ("Starting Deploy").

I can input "jqzoom" instead of the link to your repo, this is when the "cannot determine license" problem occurs:

![jqzoom webjar 2](https://cloud.githubusercontent.com/assets/15999515/18125502/2e70c5f6-6f7f-11e6-8bb5-c1c59a878df0.png)

However, I'm not sure it's referring to your repo in this case.

Could this be a problem on your side? Or should I file an issue over at the WebJars.org people?

**Comment by gregra81** [comment]
I see. Then don't even use this repo, use this one instead - https://github.com/kangax/jqzoom.git

**Comment by YoanaIvanova** [comment]
Tried that one as well, but I get this error:

`Failed! /tmp/git448413842129651792/https:/github.com/kangax/jqzoom/bower.json (No such file or directory)`

Looks like it isn't a bower repo?

**Comment by gregra81** [comment]
@YoanaIvanova - The problem is that original repo doesn't use a bower.json file.
Anyhow, I've registered this repo as jqzoom2, so it should work now - please give it another try

**Comment by YoanaIvanova** [comment]
Again, It finds the repo, but the "Version" dropdown is blank and "Deploy!" is disabled. :(

![jqzoom webjar 3](https://cloud.githubusercontent.com/assets/15999515/18159000/5491faba-702f-11e6-8745-80f6fe0b5f98.png)

(Thanks a lot for helping out!)

**Comment by gregra81** [comment]
Try the github link

**Comment by YoanaIvanova** [comment]
The same thing happens when using the GitHub link (https://github.com/gregra81/jqzoom.git) - "Version" dropdown is empty, "Deploy" button is disabled. :(

**Comment by gregra81** [comment]
Then you should talk with the webjar guys

**Comment by YoanaIvanova** [comment]
I just opened an issue, hope they can solve it. :) No need to keep this one opened, so I'm closing it.

Thanks again for all your help!
